### ISSUE TITLE
conceptual review of swap_both

### ISSUE THREAD

**Issue by mccalluc** [WGBH/aws-wrapper#6]
@afred: Not quite a code review, but I'd like it if we could go through swap_both.rb, make sure it makes sense to you (code organization and the sequence of API calls), and figure out the next step.

**Comment by afred** [comment]
Without diving too much into the code, I think the logic is OK. Some other thoughts on design...

1. Overriding `initialize` with modules is an undesirable pattern. Better to
   pass a block to `included`. If the order of inclusion is important, then that
   implies that the inheritance order is important, and if that's the case, you
   should probably be using classes instead of modules.

   If the inclusion order is not important, which it does not appear to be
   in this case, then using the `included` callback should do what you want, without
   mutzing with the initialization sequence of class ancestors.

   And actually, in this case, it looks like the logic within the `initialize`
   methods could be refactored to use a lazy-load pattern, e.g.:

    ```ruby
    # Instead of this...
    # def initialize
    #  super
    #  @dns_client = Aws::Route53::Client.new(CLIENT_CONFIG)
    # end
    #
    # ... do this
    def dns_client
      @dns_client ||= Aws::Route53::Client.new(CLIENT_CONFIG)
    end
    ```

1. Why is the `lookup` method not encapsulated in `DnsWrapper`, or other
module/object? In general, I try to put nearly all logic into objects, and try
to limit the responsibility of scripts to providing a CLI. Mainly this is
to make testing easier. Testing methods defined in scripts intended to be
run from CLI is tricky.

1. Unnecessary use of `Singleton`? Weak opinion on this, but unless we have a
requirement for "only one instance", I don't think implementing `Singleton`
makes anything clearer or more functional.

1. Maybe a bug in `aws-sdk`?

  ```
  # Unless I require 'set' I get:
  #   uninitialized constant Aws::Log::ParamFilter::Set (NameError)
  #   from /Users/chuck_mccallum/.rvm/gems/ruby-2.0.0-p481/gems/aws-sdk-core-2.1.23/lib/aws-sdk-core/log/formatter.rb:89:in `new'
  # Was not able to make a minimal reproducer.
  ```

1. If we are going to start using this stuff we need some tests. We could set
up test infrastructure on AWS, or use mocks to assert that we're sending the right
messages to the `aws-sdk` interface. Both would be nice. We should also
start doing a normal PR workflow so code reviews are nicely scoped.
